Update maven.yml
Add MySQL

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -18,19 +18,22 @@ jobs:
   build:
 
     runs-on: ubuntu-latest
-    services:
-      mariadb:
-        image: mariadb:latest
-        ports:
-          - 3306
-        env:
-          MYSQL_USER: root
-          MYSQL_PASSWORD: 12345
-          MYSQL_DATABASE: course_work
-          MYSQL_ROOT_PASSWORD: 12345
-        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
+    # services:
+    #   mariadb:
+    #     image: mariadb:latest
+    #     ports:
+    #       - 3306
+    #     env:
+    #       MYSQL_USER: root
+    #       MYSQL_PASSWORD: 12345
+    #       MYSQL_DATABASE: course_work
+    #       MYSQL_ROOT_PASSWORD: 12345
+    #     options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
 
     steps:
+    - name: Shutdown Ubuntu MySQL (SUDO)
+      run: sudo service mysql stop # Shutdown the Default MySQL, "sudo" is necessary, please not remove it
+    
     - uses: actions/checkout@v3
     - name: Set up JDK 17
       uses: actions/setup-java@v3
@@ -42,13 +45,25 @@ jobs:
 
     - uses: actions/checkout@v1
 
-    - name: Verify MariaDB connection
-      env:
-          PORT: ${{ job.services.mariadb.ports[3306] }}
-      run: |
-          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
-            sleep 1
-          done          
+    # - name: Verify MariaDB connection
+    #   env:
+    #       PORT: ${{ job.services.mariadb.ports[3306] }}
+    #   run: |
+    #       while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
+    #         sleep 1
+    #       done     
+    - name: Set up MySQL
+      uses: mirromutth/mysql-action@v1.1
+      with:
+        # host port: 3800 # Optional, default value is 3306. The port of host
+        # container port: 3307 # Optional, default value is 3306. The port of container
+        character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
+        collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
+        mysql version: '8.0.33' # Optional, default value is "latest". The version of the MySQL
+        mysql database: 'course_work'
+        mysql root password: '12345'
+        mysql user: 'root'
+        mysql password: '12345'
 
     - name: Build with Maven
       run: mvn -B package --file Program/tradeCompany/pom.xml
